apiVersion: backstage.io/v1alpha1
kind: Scorecard
metadata:
  name: observability-scorecard
  title: Observability Excellence Scorecard
  description: Measures the observability maturity of services
spec:
  targets:
    - kind: Component
      type: service
  levels:
    - name: Bronze
      description: Basic observability
      badge: 🥉
      minScore: 60
    - name: Silver
      description: Good observability practices
      badge: 🥈
      minScore: 75
    - name: Gold
      description: Excellent observability
      badge: 🥇
      minScore: 90
    - name: Platinum
      description: World-class observability
      badge: 💎
      minScore: 95
  
  categories:
    - id: monitoring
      name: Monitoring & Metrics
      weight: 30
      checks:
        - id: golden-signals
          name: Golden Signals Dashboard
          description: Service has dashboards for latency, traffic, errors, and saturation
          weight: 25
          automated: true
          query: |
            datadog.dashboard.exists(
              tags: ["service:${service.name}", "type:golden-signals"]
            )
          scoring:
            pass: 100
            fail: 0
            
        - id: custom-metrics
          name: Business Metrics
          description: Service emits custom business metrics
          weight: 20
          automated: true
          query: |
            datadog.metrics.count(
              namespace: "custom.${service.name}.*"
            ) > 10
          scoring:
            pass: 100
            partial: 50
            fail: 0
            
        - id: slo-defined
          name: SLO Definition
          description: Service has defined SLOs with error budgets
          weight: 25
          automated: true
          query: |
            datadog.slo.exists(
              tags: ["service:${service.name}"]
            )
          scoring:
            pass: 100
            fail: 0
            
        - id: alert-quality
          name: Alert Quality Score
          description: Alerts have low false positive rate
          weight: 20
          automated: true
          query: |
            datadog.monitors.false_positive_rate(
              tags: ["service:${service.name}"]
            ) < 0.05
          scoring:
            pass: 100
            warning: 70
            fail: 0
            
        - id: dashboard-usage
          name: Dashboard Active Usage
          description: Dashboards are actively viewed and used
          weight: 10
          automated: true
          query: |
            datadog.dashboard.views_last_30d(
              tags: ["service:${service.name}"]
            ) > 100
          
    - id: alerting
      name: Alerting & Incident Response
      weight: 25
      checks:
        - id: alert-coverage
          name: Alert Coverage
          description: Critical paths have appropriate alerting
          weight: 30
          checklist:
            - Availability alerts configured
            - Latency alerts configured
            - Error rate alerts configured
            - Resource saturation alerts configured
            
        - id: alert-fatigue
          name: Alert Fatigue Prevention
          description: Alerts are actionable with minimal noise
          weight: 25
          automated: true
          query: |
            datadog.monitors.noise_ratio(
              tags: ["service:${service.name}"]
            ) < 0.1
            
        - id: runbook-quality
          name: Runbook Quality
          description: Comprehensive runbooks with clear remediation steps
          weight: 25
          checklist:
            - Service overview and architecture
            - Common issues and resolutions
            - Debug commands included
            - Escalation matrix defined
            - Recovery procedures documented
            
        - id: mttr-target
          name: MTTR Performance
          description: Mean time to recovery meets targets
          weight: 20
          automated: true
          query: |
            incidents.mttr(
              service: "${service.name}",
              period: "last_30d"
            ) < 15
            
    - id: tracing
      name: Distributed Tracing
      weight: 20
      checks:
        - id: trace-coverage
          name: Trace Coverage
          description: All endpoints have distributed tracing
          weight: 40
          automated: true
          query: |
            datadog.apm.service_coverage(
              service: "${service.name}"
            ) > 0.95
            
        - id: trace-quality
          name: Trace Quality
          description: Traces include relevant tags and metadata
          weight: 30
          checklist:
            - Request IDs propagated
            - User context included
            - Error details captured
            - Custom spans for critical operations
            
        - id: trace-sampling
          name: Intelligent Sampling
          description: Appropriate sampling strategy configured
          weight: 30
          automated: true
          query: |
            datadog.apm.sampling_config(
              service: "${service.name}"
            ).strategy == "adaptive"
            
    - id: logging
      name: Logging & Diagnostics
      weight: 15
      checks:
        - id: structured-logging
          name: Structured Logging
          description: Logs use structured format with consistent fields
          weight: 35
          automated: true
          query: |
            datadog.logs.structured_percentage(
              service: "${service.name}"
            ) > 0.90
            
        - id: log-levels
          name: Appropriate Log Levels
          description: Log levels used correctly
          weight: 25
          checklist:
            - ERROR for exceptions
            - WARN for degraded conditions
            - INFO for business events
            - DEBUG disabled in production
            
        - id: correlation-ids
          name: Correlation IDs
          description: Logs include trace and request correlation IDs
          weight: 25
          automated: true
          query: |
            datadog.logs.correlation_id_percentage(
              service: "${service.name}"
            ) > 0.95
            
        - id: log-retention
          name: Log Retention Policy
          description: Appropriate retention for compliance and debugging
          weight: 15
          checklist:
            - 30-day retention for errors
            - 7-day retention for warnings
            - 3-day retention for info/debug
            
    - id: ownership
      name: Ownership & Documentation
      weight: 10
      checks:
        - id: oncall-rotation
          name: On-Call Rotation
          description: Service has defined on-call rotation
          weight: 30
          automated: true
          query: |
            pagerduty.rotation.exists(
              service: "${service.name}"
            )
            
        - id: documentation
          name: Service Documentation
          description: Comprehensive documentation maintained
          weight: 30
          checklist:
            - README with setup instructions
            - Architecture diagrams
            - API documentation
            - Deployment procedures
            
        - id: knowledge-sharing
          name: Knowledge Sharing
          description: Regular knowledge transfer sessions
          weight: 20
          manual: true
          evidence: "Links to recorded sessions or meeting notes"
          
        - id: incident-reviews
          name: Incident Reviews
          description: Post-mortems conducted for significant incidents
          weight: 20
          automated: true
          query: |
            incidents.postmortem_percentage(
              service: "${service.name}",
              severity: ["P1", "P2"]
            ) > 0.90

  scoring:
    calculation: weighted_average
    display:
      format: percentage
      precision: 0
    thresholds:
      excellent: 90
      good: 75
      needs_improvement: 60
      poor: 0
      
  automation:
    schedule: "0 0 * * MON"  # Weekly on Monday
    notifications:
      - type: slack
        channel: platform-team
        conditions:
          - score_decreased: 5
          - score_below: 75
      - type: email
        recipients: ["platform-team@company.com"]
        conditions:
          - monthly_summary: true
          
  reports:
    - id: monthly-observability-report
      name: Monthly Observability Report
      schedule: "0 9 1 * *"  # First day of month at 9 AM
      recipients:
        - platform-team@company.com
        - engineering-leadership@company.com
      content:
        - overall_scores
        - score_trends
        - top_improvements
        - areas_needing_attention
        - detailed_breakdown
        
    - id: quarterly-executive-summary
      name: Quarterly Executive Summary
      schedule: "0 9 1 */3 *"  # Every quarter
      recipients:
        - cto@company.com
        - vp-engineering@company.com
      content:
        - executive_summary
        - key_metrics
        - improvement_trajectory
        - investment_recommendations